### ISSUE TITLE
Error "setOrderings"

### ISSUE THREAD

**Issue by KonstantinSoelch** [BastianBalthasarBux/tt_address#2] opened 2017-06-23 10:43 UTC
I guess the method `setOrderings` was removed from the `QuerySettings`.

I've removed the Lines in the Controller.

**Comment by BastianBalthasarBux** [comment] 2017-06-23 12:03
Is this on TYPO3 8.7?

**Comment by KonstantinSoelch** [comment] 2017-06-23 12:05
yes, Typo3 8.7.2. Should have written that in the Issue my bad.

**Comment by BastianBalthasarBux** [comment] 2017-06-23 12:37
Could you tell me the exact error message? AFAICS setOrderings is indeed part of the QueryInterface:
https://api.typo3.org/typo3cms/current/html/interface_t_y_p_o3_1_1_c_m_s_1_1_extbase_1_1_persistence_1_1_query_interface.html#ae2c299000e9b0b90883c863012018c83

**Comment by KonstantinSoelch** [comment] 2017-06-26 07:09
![image](https://user-images.githubusercontent.com/22169163/27528103-182abde0-5a4f-11e7-9c30-7da678192121.png)

The method call is in `AddressController`.

**Comment by BastianBalthasarBux** [comment] 2017-06-27 20:30
Hmm, yeah, I know where the call is made.
The problem is: removing it means losing sorting, so it is just a dirty fix of that error message, but not a real solution.
And ATM i cannot see, that this method has been removed (or made deprecated before), as you can see at the link to the docu I provided ...
I will have a deeper look at it on a 8.x

**Comment by BastianBalthasarBux** [comment] 2018-05-25 17:09
Fixed in current master by merging contribution of fgebauer.

**Closed by BastianBalthasarBux** 2018-05-25 17:09 UTC
